### ISSUE TITLE
[Bug]: Saving MQTT config via web interface on Heltec v3 doesn't work

### ISSUE THREAD

**Issue by Calimerorulez** [meshtastic/js#90]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.3.1

### Description

Trying to save MQTT config via web interface doesn't work.

### Relevant log output

```Shell
Console output Chrome:

index-nsbd6Oaw.js:84 Uncaught (in promise) TypeError: o.toBinary is not a function
    at zg (index-nsbd6Oaw.js:84:14940)
    at Vg (index-nsbd6Oaw.js:84:14228)
    at Object.writeMessage (index-nsbd6Oaw.js:84:11921)
    at i.toBinary (index-nsbd6Oaw.js:83:29735)
    at zg (index-nsbd6Oaw.js:84:14940)
    at Vg (index-nsbd6Oaw.js:84:14228)
    at Object.writeMessage (index-nsbd6Oaw.js:84:11921)
    at i.toBinary (index-nsbd6Oaw.js:83:29735)
    at zg (index-nsbd6Oaw.js:84:14940)
    at Vg (index-nsbd6Oaw.js:84:14228)
```

**Comment by Hunter275** [comment]
The issue is in the toBinary() call when preparing to send the moduleConfig to the device. I believe it is failing due to the model for MQTT config being incorrect. 

Working on a fix.

**Comment by Hunter275** [comment]
> I can confirm the same problem. I think commit 6113924e462fabf63a2e9f8b841add0aaa4362fe broke it. Rolling it back allows me to enable MQTT now.

https://github.com/meshtastic/web/commit/6113924e462fabf63a2e9f8b841add0aaa4362fe
